//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblUyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUyeler()
        {
            this.TblCezalar = new HashSet<TblCezalar>();
            this.TblHareket = new HashSet<TblHareket>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="Adı boş bırakamazsınız.")]
        [StringLength(20,ErrorMessage ="En fazla 20 karakter girebilirsiniz.")]
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Mail { get; set; }
        public string KullanıcıAdı { get; set; }
        [StringLength(10, ErrorMessage = "En fazla 10 karakter girebilirsiniz.")]
        public string Sifre { get; set; }
        public string Fotoğraf { get; set; }
        public string TelefonNo { get; set; }
        public string Okul { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCezalar> TblCezalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHareket> TblHareket { get; set; }
    }
}
