//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblYazar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblYazar()
        {
            this.TblKitap = new HashSet<TblKitap>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="Yazar Adýný boþ geçemezsiniz.")]
        [StringLength(20,ErrorMessage ="Yazar Adý 20 karakterden uzun olamaz.")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Yazar Soyadýný boþ geçemezsiniz.")]
        [StringLength(20, ErrorMessage = "Yazar Soyadý 20 karakterden uzun olamaz.")]
        public string Soyad { get; set; }
        public string Detay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKitap> TblKitap { get; set; }
    }
}
